---

- hosts: all
  remote_user: ubuntu
  serial: 1
  pre_tasks:
    - name: Gathering EC2 facts
      action: ec2_facts

    - name: Suspend Austoscaling
      ec2_asg:
        name: "{{ ASG_NAME }}"
        suspend_processes: Launch

    - name: Deregister instance from Target Group to restart Tomcat
      local_action:
        module: elb_target
        profile: "{{ aws_profile }}"
        target_group_name: "{{ TG_NAME }}"
        target_id: "{{ ansible_ec2_instance_id }}"
        aws_region: "{{ aws_region }}"
        state: absent

  roles:
    - deployment

  post_tasks:
    - name: Registering instance back to Target Group
      local_action:
        module: elb_target
        profile: "{{ aws_profile }}"
        target_id: "{{ ansible_ec2_instance_id }}"
        target_group_name: "{{ TG_NAME }}"
        aws_region: "{{ aws_region }}"
        state: present

    - name: Resume Austoscaling
      ec2_asg:
        name: "{{ ASG_NAME }}"
        suspend_processes: []

  vars_files:
    - "group_vars/main.yml"
