---

- name: Delete document root folder
  file:
    state: absent
    path: /var/www/mediawiki
  become: true

- name: Get latest zip from s3
  aws_s3:
    bucket: mediawiki-deployment-zip
    object: builds/{{ build-number }}/mediawiki.tar
    dest: /var/www/
    mode: get

- name: Extract mediawiki tar
  unarchive:
    src: /home/cemtos/mediawiki.tar
    dest: /var/www
  become: true

- name: Set permissions mediawiki
  file:
    path: /var/www/mediawiki
    owner: apache
    group: apache
  become: true

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  become: true