- name: Install Lamp server
  yum:
    name: 
      - unzip
      - python3-pip
      - wget
      - httpd
      - php
      - php-mysql
      - php-gd
      - php-xml
      - mariadb-server
      - mariadb
      - php-mbstring
    state: latest
  become: true

- name: Start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: true

- name: Autostart httpd server
  service:
    name: httpd
    enabled: yes
  become: true

- name: Copy mysql script
  copy: 
    src: ../files/mysql_setup.sh
    dest: /home/centos
    owner: centos
    group: centos

- name: Mysql setup script
  script:
    cmd: /home/centos/mysql-setup.sh
  become: true 
  
- name: Create a new database for wiki
  mysql_db:
    name: wikidatabase
    state: present

- name: Create wiki user in mysql
  mysql_user:
    name: wiki
    password: shouldBeChanged
    priv: 'wikidatabase.*:ALL'
    state: present

- name: Download Media Wiki
  get_url:
    url: https://resource-softwares-files.s3.ap-south-1.amazonaws.com/mediawiki.tar
    dest: /home/centos

- name: Extract mediawiki tar
  unarchive:
    src: /home/centos/mediawiki.tar
    dest: /var/www/
    remote_src: true
  become: true

- name: Rename mediawiki
  shell: mv mediawiki-1.34.2 mediawiki
  args:
    chdir: /var/www/
  become: true

- name: Remove existing conf file
  file:
    path: /etc/httpd/conf/httpd.conf
    state: absent
  become: true

- name: Update document root
  copy:
    src: ../files/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
  become: true

- name: Set permissions mediawiki
  file:
    path: /var/www/mediawiki
    owner: apache
    group: apache
  become: true

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  become: true