- name: Install Lamp server
  yum:
    name: "{{ item }}"
    state: latest
    with_items:
      - unzip
      - wget
      - httpd
      - php
      - php-mysql
      - php-gd
      - php-xml
      - mariadb-server
      - mariadb
      - php-mbstring
    become: true

- name: Start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: true

- name: Autostart httpd server
  service:
    name: httpd
    enabled: yes
  become: true

- name: Create a new database for wiki
  mysql_db:
    name: wikidatabase
    state: present

- name: Create wiki user in mysql
  mysql_user:
    name: wiki
    password: shouldBeChanged
    priv: 'wikidatabase.*'
    state: present

- name: Download Media Wiki
  get_url:
    url: https://resource-softwares-files.s3.ap-south-1.amazonaws.com/mediawiki.tar
    dest: /home/centos

- name: Extract mediawiki tar
  unarchive:
    src: /home/cemtos/mediawiki.tar.gz
    dest: /var/www
  become: true

- name: Set permissions mediawiki
  file:
    path: /var/www/mediawiki
    owner: apache
    group: apache
  become: true

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  become: true